export interface BarangayTheme {
  primary: string;
  secondary: string;
  accent: string;
}

export interface BarangayInfo {
  id: string;
  name: string;
  slug: string;
  theme: BarangayTheme;
  description: string;
  captain: string;
  population: string;
  sealUrl?: string;
}

export const BARANGAYS: BarangayInfo[] = [
  {
    id: "poblacion",
    slug: "poblacion",
    name: "Barangay Poblacion",
    description: "The urban center and seat of commerce in Talibon.",
    captain: "Hon. Juan Dela Cruz",
    population: "5,420",
    theme: { primary: "#0f4c81", secondary: "#f5f5f5", accent: "#ffb703" },
  },
  {
    id: "san-jose",
    slug: "san-jose",
    name: "Barangay San Jose",
    description: "A thriving agricultural community in the heart of Talibon.",
    captain: "Hon. Maria Santos",
    population: "3,150",
    theme: { primary: "#1a4731", secondary: "#f8f9fa", accent: "#bc6c25" },
  },
  {
    id: "san-roque",
    slug: "san-roque",
    name: "Barangay San Roque",
    description: "Known for its coastal beauty and vibrant fishing community.",
    captain: "Hon. Roberto Gomez",
    population: "4,200",
    theme: { primary: "#780000", secondary: "#fff1f2", accent: "#003049" },
  },
  {
    id: "bagacay",
    slug: "bagacay",
    name: "Barangay Bagacay",
    description: "A peaceful residential area with a strong sense of community.",
    captain: "Hon. Pedro Penduko",
    population: "2,800",
    theme: { primary: "#432818", secondary: "#fdf0d5", accent: "#669bbc" },
  },
  {
    id: "balintawak",
    slug: "balintawak",
    name: "Barangay Balintawak",
    description: "Historically significant and community-focused.",
    captain: "Hon. Clara Recto",
    population: "3,400",
    theme: { primary: "#386641", secondary: "#f2e8cf", accent: "#a7c957" },
  },
  {
    id: "burgos",
    slug: "burgos",
    name: "Barangay Burgos",
    description: "Contributing to the agricultural productivity of the municipality.",
    captain: "Hon. Antonio Luna",
    population: "2,100",
    theme: { primary: "#5e503f", secondary: "#eae0d5", accent: "#c9ada7" },
  },
  {
    id: "cabasacan",
    slug: "cabasacan",
    name: "Barangay Cabasacan",
    description: "A vibrant neighborhood with rich local traditions.",
    captain: "Hon. Melchora Aquino",
    population: "3,050",
    theme: { primary: "#003e1f", secondary: "#e8f5e9", accent: "#ff9800" },
  },
  {
    id: "calituban",
    slug: "calituban",
    name: "Barangay Calituban",
    description: "An island barangay famous for its crystal clear waters.",
    captain: "Hon. Lapu-Lapu",
    population: "4,800",
    theme: { primary: "#0077b6", secondary: "#caf0f8", accent: "#f4a261" },
  },
  {
    id: "cataban",
    slug: "cataban",
    name: "Barangay Cataban",
    description: "Home to resilient fishing families and scenic views.",
    captain: "Hon. Dagohoy",
    population: "3,900",
    theme: { primary: "#023e8a", secondary: "#f0f8ff", accent: "#ee9b00" },
  },
  {
    id: "guindacpan",
    slug: "guindacpan",
    name: "Barangay Guindacpan",
    description: "A coastal treasure with a deep love for the sea.",
    captain: "Hon. Sikatuna",
    population: "4,150",
    theme: { primary: "#005f73", secondary: "#e0f2f1", accent: "#9b2226" },
  },
  {
    id: "magsaysay",
    slug: "magsaysay",
    name: "Barangay Magsaysay",
    description: "Developing area with focus on sustainable livelihood.",
    captain: "Hon. Ramon Magsaysay",
    population: "2,950",
    theme: { primary: "#2b2d42", secondary: "#edf2f4", accent: "#ef233c" },
  },
  {
    id: "mahanay",
    slug: "mahanay",
    name: "Barangay Mahanay",
    description: "An island paradise known for hospitality.",
    captain: "Hon. Felipe Segundo",
    population: "3,600",
    theme: { primary: "#1b4332", secondary: "#d8f3dc", accent: "#40916c" },
  },
  {
    id: "nocnocan",
    slug: "nocnocan",
    name: "Barangay Nocnocan",
    description: "A quiet island escape with pristine environments.",
    captain: "Hon. Inocencio",
    population: "2,300",
    theme: { primary: "#252422", secondary: "#fffcf2", accent: "#eb5e28" },
  },
  {
    id: "nueva-esperanza",
    slug: "nueva-esperanza",
    name: "Barangay Nueva Esperanza",
    description: "Bringing hope and progress through unity.",
    captain: "Hon. Esperanza",
    population: "1,950",
    theme: { primary: "#3d405b", secondary: "#f4f1de", accent: "#e07a5f" },
  },
  {
    id: "rizal",
    slug: "rizal",
    name: "Barangay Rizal",
    description: "Commemorating national heritage through local action.",
    captain: "Hon. Jose Rizal",
    population: "4,050",
    theme: { primary: "#14213d", secondary: "#e5e5e5", accent: "#fca311" },
  },
  {
    id: "sag",
    slug: "sag",
    name: "Barangay Sag",
    description: "A small but energetic barangay with a big heart.",
    captain: "Hon. Samuel Sag",
    population: "1,800",
    theme: { primary: "#312244", secondary: "#e0e1dd", accent: "#778da9" },
  },
  {
    id: "san-agustin",
    slug: "san-agustin",
    name: "Barangay San Agustin",
    description: "Devoted to progress and spiritual heritage.",
    captain: "Hon. Agustin",
    population: "3,200",
    theme: { primary: "#4a4e69", secondary: "#f2e9e4", accent: "#9a8c98" },
  },
  {
    id: "san-francisco",
    slug: "san-francisco",
    name: "Barangay San Francisco",
    description: "A growing community with a bright future.",
    captain: "Hon. Francisco",
    population: "2,750",
    theme: { primary: "#22223b", secondary: "#c9ada7", accent: "#4a4e69" },
  },
  {
    id: "san-isidro",
    slug: "san-isidro",
    name: "Barangay San Isidro",
    description: "Patron of farmers, heart of agriculture.",
    captain: "Hon. Isidro",
    population: "3,450",
    theme: { primary: "#606c38", secondary: "#fefae0", accent: "#dda15e" },
  },
  {
    id: "san-pedro",
    slug: "san-pedro",
    name: "Barangay San Pedro",
    description: "A community built on faith and hard work.",
    captain: "Hon. Pedro",
    population: "3,100",
    theme: { primary: "#432818", secondary: "#fdf0d5", accent: "#8d99ae" },
  },
  {
    id: "santo-nino",
    slug: "santo-nino",
    name: "Barangay Santo Niño",
    description: "Dedicated to the holy child and community youth.",
    captain: "Hon. Benigno",
    population: "4,600",
    theme: { primary: "#283618", secondary: "#fefae0", accent: "#bc6c25" },
  },
  {
    id: "sikatuna",
    slug: "sikatuna",
    name: "Barangay Sikatuna",
    description: "A symbol of friendship and local partnership.",
    captain: "Hon. Katunao",
    population: "2,400",
    theme: { primary: "#582f0e", secondary: "#fefae0", accent: "#e85d04" },
  },
  {
    id: "suba",
    slug: "suba",
    name: "Barangay Suba",
    description: "A riverside community with a focus on commerce.",
    captain: "Hon. Subas",
    population: "5,100",
    theme: { primary: "#001d3d", secondary: "#e0e1dd", accent: "#ffc300" },
  },
  {
    id: "tanghaligue",
    slug: "tanghaligue",
    name: "Barangay Tanghaligue",
    description: "Strategic location with potential for industrial growth.",
    captain: "Hon. Hali",
    population: "2,250",
    theme: { primary: "#1d3557", secondary: "#f1faee", accent: "#e63946" },
  },
  {
    id: "zamura",
    slug: "zamura",
    name: "Barangay Zamura",
    description: "A peaceful boundary barangay with vast green spaces.",
    captain: "Hon. Zamora",
    population: "2,050",
    theme: { primary: "#344e41", secondary: "#dad7cd", accent: "#588157" },
  }
];
